name: Netlify Preview Deployment

on:
  pull_request:
    branches:
      - main
    
jobs:
  Preview:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/labeler@v2
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: "Deployed preview site"
        run: curl -X POST -d {} ${{ secrets.NETLIFY_PREVIEW_BUILD_HOOK }}
